"""
Django settings for Nexify project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from django.conf import settings
import os
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fom^m+o)!2mi--%d1z&qtr-k10umqgz^q2hie^4)yx&g6mmmb5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production

# Allowed Hosts (only allow domains that host your Django app)
# ALLOWED_HOSTS = [
#     '34.93.63.198:8005',
#     '34.93.63.198',
#     'localhost',  # For local development
#     '127.0.0.1',   # For local development
#     '192.168.0.121:3000',
#     '192.168.0.123:3000',
#     'localhost:3000',
#     '192.168.0.134',
#     'nexify.indusvision.ai', 
#     '00cb-2409-40f0-2016-1d6-4e9e-51f8-8ded-4dff.ngrok-free.app',
#     '088b0104e565213bdb62b71101e32e1d.serveo.net',
#     '192.168.1.80',
#     '192.168.0.102',
#     '192.168.1.3:3000',
#     '192.168.0.109:3000'
    
# ]

ALLOWED_HOSTS = ['*']
CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_ALLOW_ALL = True
CSRF_TRUSTED_ORIGINS = [
    'http://*',
    'https://*',
]


# CORS Configuration (only allow specific origins)
# CORS_ALLOW_ALL_ORIGINS = False  # Disable this for security
# CORS_ORIGIN_ALLOW_ALL = False   # Disable this for security

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',    # Frontend development
#     'http://localhost:3001',    # Frontend development
#     'http://localhost:8006',    # Alternative local port
#     'http://localhost:8001',
#     'http://nexify.indusvision.ai',
#     'http://localhost:3001',    # Frontend development
#     'http://34.93.63.198:8005',
#     'http://192.168.0.121:3000',
#     'http://192.168.0.123:3000',
#     'http://192.168.0.134:8000',
#     'http://192.168.1.80:8000',
#     'http://192.168.0.102:3000',
#     'http://192.168.0.102:3001',
#     'http://192.168.1.3:3000',
#     'http://192.168.0.109:3000'

# ]

# CSRF Configuration
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:8001',
#     'http://nexify.indusvision.ai',
#     'http://localhost:3000',    # Only include in development
#     'http://localhost:3001',    # Frontend development,
#     'http://34.93.63.198:8005',
#     'http://192.168.0.134:8000',
#     'http://192.168.0.121:3000',
#     'http://192.168.0.123:3000',
#     'http://192.168.1.80:8000',
#     'http://192.168.0.102:3000',
#     'http://192.168.0.102:3001',
#     'http://192.168.1.3:3000',
#     'http://192.168.0.109:3000'
# ]
# # Security Headers
# CSRF_COOKIE_SECURE = True       # Only send CSRF cookie over HTTPS
# SESSION_COOKIE_SECURE = True    # Only send session cookie over HTTPS
# # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # If using a reverse proxy

# # Optional: For APIs that need credentials
# CORS_ALLOW_CREDENTIALS = True

# # Optional: Fine-grained CORS controls
# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'users',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'import_export',
    'django_celery_beat',
    'workspace'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Nexify.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend', 'dist'),  # Add this path where your index.html is located
            os.path.join(BASE_DIR, 'templates'),       # Keep your original templates path
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Nexify.wsgi.application'

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,  # Set to False if you're using Token/JWT authentication
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        },
    },
    'PERSIST_AUTH': True,
    'SCHEMA_URL': 'http://localhost:8001/swagger.json'
}



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#         'default': 
#             {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': 'AnamolyDevDB',
#             'USER': 'vin',    
#             'PASSWORD': 'Nexify@025',    
#             'HOST': '34.93.63.198',    
#             'PORT': '3306',
#             }
# }

AUTH_USER_MODEL = 'users.CustomUser'


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
    "ROTATE_REFRESH_TOKENS": False, 
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": settings.SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}  

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

CELERY_BROKER_URL = 'redis://nexify_redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://nexify_redis:6379/0'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'frontend', 'dist', 'assets')]
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'


CELERY_BEAT_SCHEDULE = {
    'update-disposable-emails-every-24-hours': {
        'task': 'users.tasks.update_disposable_email_domains',
        'schedule': timedelta(hours=24),  # ✅ Run every 24 hours
    }
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = os.getenv("EMAIL_PORT")
APPLICATION_EMAIL = os.getenv('APPLICATION_EMAIL')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
